### ISSUE TITLE
Camel Idea Plugin 1.2.8 not working with IntelliJ IDEA 2024.1.4

### ISSUE THREAD

**Issue by mjga-trifork** [camel-tooling/camel-idea-plugin#1031]
I can for the life of me not get the 1.2.8 plugin to work with IntelliJ IDEA 2024.1.4 (Ultimate Edition).
Is this version of the plugin not compatible with this version of IntelliJ?

I get a lot of these errors in the IntelliJ log, but it's the only Camel Idea Plugin related logs i can find:
```
WARN - #c.i.i.s.i.StartupManagerImpl - Migrate com.github.cameltooling.idea.CamelPluginStartup to ProjectActivity [Plugin: org.apache.camel]
com.intellij.diagnostic.PluginException: Migrate com.github.cameltooling.idea.CamelPluginStartup to ProjectActivity [Plugin: org.apache.camel]
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:276)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:68)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invokeSuspend(StartupManagerImpl.kt:191)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3.invokeSuspend(StartupManagerImpl.kt:190)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

Let me know if you need more information.

**Comment by davsclaus** [comment]
I use the community version of 2014.1.2 and I dont get any kind of WARNs.

**Comment by davsclaus** [comment]
Upgraded to 2014.1.4 community and I cannot see these WARNs

**Comment by davsclaus** [comment]
I guess its a WARN about that the plugin should be migrated some code to newer APIs.

**Comment by davsclaus** [comment]
Can you try 1.2.9 release

**Comment by mjga-trifork** [comment]
1.2.9 made no apparent difference.
![image](https://github.com/camel-tooling/camel-idea-plugin/assets/121794731/0eaf0c90-ceef-4850-953c-69b4618e0460)
At least I don't see the Camel icon to the left of my route, and I get no code suggestions:
![image](https://github.com/camel-tooling/camel-idea-plugin/assets/121794731/3b127e17-9539-4af3-a2f4-3068d6d0cb21)

I don't know if it's important, but it might be of use to know, that this is a Kotlin based Spring Boot 3 project and we're using Gradle.

**Comment by davsclaus** [comment]
1) is the WARN gone

2) okay can you try loading a plain java based maven project

**Comment by mjga-trifork** [comment]
> 1. is the WARN gone

Nope. I still get the exact same warning.

> 2. okay can you try loading a plain java based maven project

I cloned the ```camel-examples``` repo, and it works fine for those:
![image](https://github.com/camel-tooling/camel-idea-plugin/assets/121794731/9dafda9c-d450-4b0c-b9a4-8813efbe439d)

**Comment by essobedo** [comment]
Hi could you please a small project to reproduce?

**Comment by mjga-trifork** [comment]
Actually just creating a project with the Spring Boot Initializr reproduces it on my machine:
https://start.spring.io/#!type=gradle-project-kotlin&language=kotlin&platformVersion=3.2.8&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=camel-plugin-issue&name=camel-plugin-issue&description=camel-plugin%20issue%201031%20project&packageName=com.example.camel-plugin-issue&dependencies=camel

I am also attaching a small demo project.
[camel-plugin-issue.zip](https://github.com/user-attachments/files/16440671/camel-plugin-issue.zip)

IntelliJ IDEA 2024.1.4 (Ultimate Edition)
Camel plugin v. 1.2.9

**Comment by essobedo** [comment]
I don't get this warning with both IntelliJ IDEA 2024.1.4 Ultimate and Community Edition. Anyway, this plugin doesn't support Kotlin so I'm closing this ticket, feel free to create another ticket to add the support of Kotlin
