### ISSUE TITLE
NullpointerException in org.apache.camel.tooling.maven.MavenDownloaderImpl 

### ISSUE THREAD

**Issue by luxlabs** [camel-tooling/camel-idea-plugin#1085]
java.lang.NullPointerException: Cannot invoke "org.apache.maven.settings.Profile.getRepositories()" because the return value of "java.util.Map.get(Object)" is null
	at org.apache.camel.tooling.maven.MavenDownloaderImpl.configureDefaultRepositories(MavenDownloaderImpl.java:1223)
	at org.apache.camel.tooling.maven.MavenDownloaderImpl.doBuild(MavenDownloaderImpl.java:326)
	at org.apache.camel.support.service.BaseService.build(BaseService.java:64)
	at com.github.cameltooling.idea.maven.MavenArtifactRetrieverContext.<init>(MavenArtifactRetrieverContext.java:53)
	at com.github.cameltooling.idea.maven.MavenArtifactRetrieverContext.<init>(MavenArtifactRetrieverContext.java:57)
	at com.github.cameltooling.idea.maven.CamelMavenVersionManager.<init>(CamelMavenVersionManager.java:43)
	at com.github.cameltooling.idea.service.CamelCatalogService.loadVersion(CamelCatalogService.java:107)
	at com.github.cameltooling.idea.service.CamelService.downloadNewCamelCatalogVersion(CamelService.java:524)
	at com.github.cameltooling.idea.service.CamelService$1.run(CamelService.java:455)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$7(CoreProgressManager.java:542)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by luxlabs** [comment]
Plugin version: **1.3.3**
IntelliJ IDEA version: **2024.3.1 (Ultimate Edition)**

**Comment by davsclaus** [comment]
Do you see this all the time or only rarely ?

**Comment by luxlabs** [comment]
Every time I open a project

**Comment by davsclaus** [comment]
Fixed the NPE in Camel 4.10 and 4.8.3
