### ISSUE TITLE
Exception Popup in Idea

### ISSUE THREAD

**Issue by dschulten** [camel-tooling/camel-idea-plugin#586]
The following exception was reported in Idea:

```
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class != KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class
  which is element of OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor} and OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}
  which is 0th element of [OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}] and [OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}, OurResolveResult{element=KtLightMethodForDecompiledDeclaration of KtLightClassForDecompiledDeclaration of PsiFile:RestAssuredRestDocumentationWrapper.class, substitutor=EmptySubstitutor}]

Recomputation gives [Lcom.intellij.psi.JavaResolveResult;@1233856f (class [Lcom.intellij.psi.JavaResolveResult;) which is equivalent to 'fresh'
Recomputation log:
  Resolving PsiImportStaticReferenceElement:com.epages.restdocs.apispec.RestAssuredRestDocumentationWrapper.document of class com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:90)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:77)
	at com.intellij.psi.impl.source.resolve.ResolveCache.cache(ResolveCache.java:322)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:249)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl.multiResolve(PsiImportStaticReferenceElementImpl.java:224)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl.advancedResolve(PsiImportStaticReferenceElementImpl.java:215)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl.resolve(PsiImportStaticReferenceElementImpl.java:250)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.apache.camel.idea.gutter.CamelRouteLineMarkerProvider.resolvedIdentifier(CamelRouteLineMarkerProvider.java:170)
	at org.apache.camel.idea.gutter.CamelRouteLineMarkerProvider.isCamelRouteStartIdentifierExpression(CamelRouteLineMarkerProvider.java:149)
	at org.apache.camel.idea.gutter.CamelRouteLineMarkerProvider.collectNavigationMarkers(CamelRouteLineMarkerProvider.java:77)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:31)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:23)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:181)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:82)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:77)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by davsclaus** [comment]
Can you try with latest 0.7.x and report again if something happens
