### ISSUE TITLE
java.util.ConcurrentModificationException in 0.8.8

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#703]
```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1511)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1534)
	at com.github.cameltooling.idea.service.CamelService.containsLibrary(CamelService.java:166)
	at com.github.cameltooling.idea.catalog.CamelCatalogProvider$1.getActualProvider(CamelCatalogProvider.java:46)
	at com.github.cameltooling.idea.catalog.CamelCatalogProvider.get(CamelCatalogProvider.java:160)
	at com.github.cameltooling.idea.service.CamelCatalogService.get(CamelCatalogService.java:58)
	at com.github.cameltooling.idea.service.CamelCatalogService.loadVersion(CamelCatalogService.java:85)
	at com.github.cameltooling.idea.service.CamelService.downloadNewCamelCatalogVersion(CamelService.java:373)
	at com.github.cameltooling.idea.service.CamelService$1.run(CamelService.java:295)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by davsclaus** [comment]
@essobedo maybe you recent work has fixed this?

**Comment by essobedo** [comment]
No but I will include the fix in https://github.com/camel-tooling/camel-idea-plugin/pull/701

**Comment by essobedo** [comment]
Finally I will do it in a separate PR
