### ISSUE TITLE
Compatibility problem with intellij idea version 2023.1

### ISSUE THREAD

**Issue by humber42** [camel-tooling/camel-idea-plugin#856]
There is a problem with the compatibility of the Apache Camel plugin with the version of IntelliJ IDEA v2023.1 which does not allow it to be installed

**Comment by davsclaus** [comment]
Yeah I can install 0.9.9 on 2023.1.2 but then when I open a Camel example the plugin is grey

**Comment by davsclaus** [comment]
You can try with 0.9.8 version which you can find here on github and download and install manually

**Comment by davsclaus** [comment]
```
com.intellij.diagnostic.PluginException: class com.intellij.psi.impl.source.JavaDummyHolder cannot be cast to class com.intellij.psi.PsiJavaFile (com.intellij.psi.impl.source.JavaDummyHolder and com.intellij.psi.PsiJavaFile are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @5d366db2) [Plugin: org.apache.camel]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:99)
	at com.intellij.psi.impl.source.codeStyle.CoreCodeStyleUtil.processElementOrFail(CoreCodeStyleUtil.java:86)
	at com.intellij.psi.impl.source.codeStyle.CoreCodeStyleUtil.postProcessElement(CoreCodeStyleUtil.java:59)
	at com.intellij.formatting.service.CoreFormattingService.formatElement(CoreFormattingService.java:45)
	at com.intellij.formatting.service.FormattingServiceUtil.formatElement(FormattingServiceUtil.java:67)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:81)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.quickfix.AddTypeCastFix.createCastExpression(AddTypeCastFix.java:109)
	at com.intellij.codeInsight.daemon.impl.quickfix.CastMethodArgumentFix$MyFixerActionFactory.getModifiedArgument(CastMethodArgumentFix.java:45)
	at com.intellij.codeInsight.daemon.impl.quickfix.ArgumentFixerActionFactory.replaceWithCast(ArgumentFixerActionFactory.java:139)
	at com.intellij.codeInsight.daemon.impl.quickfix.ArgumentFixerActionFactory.lambda$registerCastActions$1(ArgumentFixerActionFactory.java:90)
	at com.intellij.util.containers.ContainerUtil.exists(ContainerUtil.java:2215)
	at com.intellij.codeInsight.daemon.impl.quickfix.ArgumentFixerActionFactory.registerCastActions(ArgumentFixerActionFactory.java:90)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightMethodUtil.registerMethodCallIntentions(HighlightMethodUtil.java:1028)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightMethodUtil.checkMethodCall(HighlightMethodUtil.java:474)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitMethodCallExpression(HighlightVisitorImpl.java:951)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:126)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:348)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:287)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.analysis.JavaNamesHighlightVisitor.analyze(JavaNamesHighlightVisitor.java:46)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:210)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:92)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:278)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:226)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:374)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:373)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:349)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:187)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:347)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassCastException: class com.intellij.psi.impl.source.JavaDummyHolder cannot be cast to class com.intellij.psi.PsiJavaFile (com.intellij.psi.impl.source.JavaDummyHolder and com.intellij.psi.PsiJavaFile are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @5d366db2)
	at com.github.cameltooling.idea.service.extension.camel.JavaCamelIdeaUtils.isCamelFile(JavaCamelIdeaUtils.java:120)
	at com.github.cameltooling.idea.util.CamelIdeaUtils.processText(CamelIdeaUtils.java:284)
	at com.github.cameltooling.idea.formatter.CamelPostFormatProcessor.processText(CamelPostFormatProcessor.java:41)
	at com.github.cameltooling.idea.formatter.CamelPostFormatProcessor.processElement(CamelPostFormatProcessor.java:33)
	at com.intellij.psi.impl.source.codeStyle.CoreCodeStyleUtil.processElementOrFail(CoreCodeStyleUtil.java:75)
	... 51 more

```

**Comment by davsclaus** [comment]
This works with 0.9.9 and Camel 3.20.5 project, however that exception above is logged but it does not prevent the plugin for working.

**Comment by davsclaus** [comment]
@essobedo have you seen the above stacktrace ?

**Comment by davsclaus** [comment]
The plugin 0.9.9 works with IDEA 2023.1.2 and Camel 3 based projects

**Comment by essobedo** [comment]
> @essobedo have you seen the above stacktrace ?

No, I didn't
