### ISSUE TITLE
Camel Plugin likely causing freezes of IntelliJ IDEA 

### ISSUE THREAD

**Issue by mklueh** [camel-tooling/camel-idea-plugin#901]
This happened to me after integrating Kotlin into my project. I'm also using WSL.

Once I've removed the Camel plugin everything works fine again.

See:

https://youtrack.jetbrains.com/issue/IDEA-293604/IntelliJ-is-slow-hanging-when-working-with-WSL-filesystem#focus=Comments-27-8070777.0-0

Here is a part of the logs. In case you can't see the files I've attached in the YouTrack issue, I'll upload them here in addition

```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE

	at java.base@17.0.8/java.io.RandomAccessFile.readBytes(Native Method)
	at java.base@17.0.8/java.io.RandomAccessFile.read(RandomAccessFile.java:405)
	at java.base@17.0.8/java.io.RandomAccessFile.readFully(RandomAccessFile.java:469)
	at java.base@17.0.8/java.util.zip.ZipFile$Source.readFullyAt(ZipFile.java:1483)
	at java.base@17.0.8/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1631)
	at java.base@17.0.8/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1450)
	at java.base@17.0.8/java.util.zip.ZipFile$Source.get(ZipFile.java:1412)
	at java.base@17.0.8/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:716)
	at java.base@17.0.8/java.util.zip.ZipFile.<init>(ZipFile.java:250)
	at java.base@17.0.8/java.util.zip.ZipFile.<init>(ZipFile.java:179)
	at java.base@17.0.8/java.util.jar.JarFile.<init>(JarFile.java:346)
	at java.base@17.0.8/jdk.internal.loader.URLClassPath$JarLoader.getJarFile(URLClassPath.java:825)
	at java.base@17.0.8/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:769)
	at java.base@17.0.8/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:762)
	at java.base@17.0.8/java.security.AccessController.executePrivileged(AccessController.java:807)
	at java.base@17.0.8/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base@17.0.8/jdk.internal.loader.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:761)
	at java.base@17.0.8/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:735)
	at java.base@17.0.8/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:499)
	at java.base@17.0.8/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:482)
	at java.base@17.0.8/java.security.AccessController.executePrivileged(AccessController.java:807)
	at java.base@17.0.8/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base@17.0.8/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:481)
	at java.base@17.0.8/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:449)
	at java.base@17.0.8/jdk.internal.loader.URLClassPath.findResource(URLClassPath.java:295)
	at java.base@17.0.8/java.net.URLClassLoader$2.run(URLClassLoader.java:629)
	at java.base@17.0.8/java.net.URLClassLoader$2.run(URLClassLoader.java:627)
	at java.base@17.0.8/java.security.AccessController.executePrivileged(AccessController.java:776)
	at java.base@17.0.8/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base@17.0.8/java.net.URLClassLoader.findResource(URLClassLoader.java:626)
	at java.base@17.0.8/java.lang.ClassLoader.getResource(ClassLoader.java:1408)
	at java.base@17.0.8/java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:290)
	at com.github.cameltooling.idea.service.CamelService.loadComponentProperties(CamelService.java:733)
	at com.github.cameltooling.idea.service.CamelService.addCustomCamelComponentsFromDependency(CamelService.java:661)
	at com.github.cameltooling.idea.service.CamelService.scanForCamelDependencies(CamelService.java:580)
	at com.github.cameltooling.idea.service.CamelService.scanForCamelProject(CamelService.java:376)
	at com.github.cameltooling.idea.CamelPluginStartup.scanForCamelProject(CamelPluginStartup.java:56)
	at com.github.cameltooling.idea.CamelPluginStartup.runActivity(CamelPluginStartup.java:35)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:327)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:72)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$2.invoke$lambda$0(StartupManagerImpl.kt:280)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$2$$Lambda$2995/0x0000000801a24b08.run(Unknown Source)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at com.intellij.openapi.project.SmartModeScheduler$addLast$1.invoke(SmartModeScheduler.kt:89)
	at com.intellij.openapi.project.SmartModeScheduler$addLast$1.invoke(SmartModeScheduler.kt:89)
	at com.intellij.openapi.project.SmartModeScheduler.addLast$lambda$0(SmartModeScheduler.kt:89)
	at com.intellij.openapi.project.SmartModeScheduler$$Lambda$2899/0x000000080197d858.accept(Unknown Source)
	at com.intellij.openapi.project.SmartModeScheduler$RunnableDelegate.run(SmartModeScheduler.kt:49)
	at com.intellij.openapi.project.SmartModeScheduler.doRun(SmartModeScheduler.kt:137)
	at com.intellij.openapi.project.SmartModeScheduler.runAllWhileSmart(SmartModeScheduler.kt:129)
	at com.intellij.openapi.project.SmartModeScheduler$$Lambda$7576/0x0000000802c1f5b0.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at com.intellij.openapi.application.impl.FlushQueue$$Lambda$827/0x0000000800783060.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base@17.0.8/java.security.AccessController.executePrivileged(AccessController.java:776)
	at java.base@17.0.8/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base@17.0.8/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue$$Lambda$712/0x00000008006b4000.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueueKt$$Lambda$708/0x00000008006a38c8.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueue$$Lambda$705/0x00000008006a6438.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

"ApplicationImpl pooled thread 13" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE

	at java.base@17.0.8/sun.nio.fs.WindowsNativeDispatcher.GetFileAttributesEx0(Native Method)
	at java.base@17.0.8/sun.nio.fs.WindowsNativeDispatcher.GetFileAttributesEx(WindowsNativeDispatcher.java:390)
	at java.base@17.0.8/sun.nio.fs.WindowsFileAttributes.get(WindowsFileAttributes.java:307)
	at java.base@17.0.8/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:51)
	at java.base@17.0.8/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at java.base@17.0.8/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
	at java.base@17.0.8/sun.nio.fs.AbstractFileSystemProvider.isRegularFile(AbstractFileSystemProvider.java:137)
	at java.base@17.0.8/java.nio.file.Files.isRegularFile(Files.java:2361)
	at org.jetbrains.kotlin.idea.core.script.ClasspathToVfsConverter.getFileType(ScriptConfigurationManager.kt:161)
	at org.jetbrains.kotlin.idea.core.script.ClasspathToVfsConverter.classpathEntryToVfs(ScriptConfigurationManager.kt:171)
	at org.jetbrains.kotlin.idea.core.script.ucache.ScriptClassRootsCache.getScriptDependenciesSourceFiles(ScriptClassRootsCache.kt:156)
	at org.jetbrains.kotlin.idea.core.script.configuration.CompositeScriptConfigurationManager.getScriptDependenciesSourceFiles(CompositeScriptConfigurationManager.kt:185)
	at org.jetbrains.kotlin.idea.core.script.ucache.KotlinScriptEntitiesKt.getActualScriptLibraries(kotlinScriptEntities.kt:295)
	at org.jetbrains.kotlin.idea.core.script.ucache.KotlinScriptEntitiesKt.syncScriptEntities(kotlinScriptEntities.kt:195)
	at org.jetbrains.kotlin.idea.core.script.ucache.KotlinScriptEntitiesKt.syncScriptEntities(kotlinScriptEntities.kt:67)
	at org.jetbrains.kotlin.idea.core.script.ucache.ScriptClassRootsUpdater.applyDiffToModel(ScriptClassRootsUpdater.kt:326)
	at org.jetbrains.kotlin.idea.core.script.ucache.ScriptClassRootsUpdater.applyDiffToModelAsync(ScriptClassRootsUpdater.kt:310)
	at org.jetbrains.kotlin.idea.core.script.ucache.ScriptClassRootsUpdater.doUpdate(ScriptClassRootsUpdater.kt:277)
	at org.jetbrains.kotlin.idea.core.script.ucache.ScriptClassRootsUpdater.doUpdate$default(ScriptClassRootsUpdater.kt:241)
	at org.jetbrains.kotlin.idea.core.script.ucache.ScriptClassRootsUpdater.ensureUpdateScheduled$lambda$10$lambda$9(ScriptClassRootsUpdater.kt:229)
	at org.jetbrains.kotlin.idea.core.script.ucache.ScriptClassRootsUpdater$$Lambda$4181/0x0000000801e80288.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1567/0x0000000800e48988.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1568/0x0000000800e48e40.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$submitTask$8(BackgroundTaskUtil.java:270)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil$$Lambda$1641/0x0000000800f33da0.run(Unknown Source)
	at java.base@17.0.8/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.8/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base@17.0.8/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base@17.0.8/java.security.AccessController.executePrivileged(AccessController.java:776)
	at java.base@17.0.8/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base@17.0.8/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)

```

**Comment by essobedo** [comment]
Hi 👋 thank you for your feedback. Do you have by chance a simple project to reproduce?

**Comment by mklueh** [comment]
@essobedo I have no reproducer and I fear creating one is too much hassle, I'm unsure if it's my setup or the project, but I can describe it a little more:

It's a Quarkus Gradle multi-module project with Gradle 8.3 and JDK 19 inside WSL, using Kotlin it worked usually until I've integrated Kotlin.

**Comment by essobedo** [comment]
Without a reproducer, it is really hard to help. According to the thread dump, it is simply scanning the dependencies on the filesystem which implies a lot of disc IO.

Have you tried to open the project using the Windows filesystem as proposed in the workaround listed in the link you provided?

**Comment by davsclaus** [comment]
You can try turn off "Scan classpath for 3rd party Camel components" in the plugin settings. This is only relevant if you have built your own components
